# 250_QUIT_line_length_boundary_510_bytes.spec
# Tests that QUIT with a large payload near the 512-byte RFC message limit is handled cleanly without corruption.
CLIENTS C1, C2

C1 SEND PASS 1234
C1 SEND NICK Ali338
C1 SEND USER ali338 0 * :Ali338
C1 EXPECT 001 Ali338 :*

C2 SEND PASS 1234
C2 SEND NICK Bob338
C2 SEND USER bob338 0 * :Bob338
C2 EXPECT 001 Bob338 :*

C1 SEND JOIN #boundary
C1 EXPECT :Ali338!* JOIN #boundary
C2 SEND JOIN #boundary
C2 WAIT_RECV :Bob338!* JOIN #boundary
C1 WAIT_RECV :Bob338!* JOIN #boundary

# Alice quits with a 200-char message
C1 SEND QUIT :AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C1 EXPECT ERROR :Closing connection
C1 EXPECT_DISCONNECT

C2 WAIT_RECV :Ali338!* QUIT :AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C2 EXPECT_CONNECTED
