# 271_PRIVMSG_oversized_outbound_line_overflow.spec
# Boundary / Buffer Overflow: Outbound line exceeding RFC 512-byte limit
# Inbound line is near 510 bytes; when prefixed with :nick!user@localhost PRIVMSG #chan :, total exceeds 512 bytes.
# Expected: Server clamps, truncates, or limits outbound messages to 512 bytes including CRLF per RFC 2812.
CLIENTS C1, C2

# Setup C1
C1 SEND PASS 1234
C1 SEND NICK Ali303
C1 SEND USER ali303 0 * :Ali303
C1 EXPECT 001 Ali303 :*

# Setup C2
C2 SEND PASS 1234
C2 SEND NICK Bob303
C2 SEND USER bob303 0 * :Bob303
C2 EXPECT 001 Bob303 :*

# Both join #boundary
C1 SEND JOIN #boundary
C1 EXPECT 366 Ali303 #boundary :End of /NAMES list
C2 SEND JOIN #boundary
C1 WAIT_RECV :Bob303!* JOIN #boundary

# C1 sends near-max length message (450 bytes)
C1 SEND PRIVMSG #boundary :AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C2 WAIT_RECV :Ali303!* PRIVMSG #boundary :AAAA*
