CLIENTS C1, C2

C1 SEND PASS 1234
C1 SEND NICK Alice
C1 SEND USER alice 0 * :Alice

C2 SEND PASS 1234
C2 SEND NICK Bob
C2 SEND USER bob 0 * :Bob

C1 SEND JOIN #disc
C2 SEND JOIN #disc
C1 WAIT_RECV :Bob!* JOIN #disc

C1 SEND QUIT :Leaving server
C2 WAIT_RECV :Alice!* QUIT :Leaving server
C1 EXPECT_DISCONNECT

C2 EXPECT_CONNECTED
C2 SEND PRIVMSG Bob :Self echo or keep-alive test
