FROM debian:12

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nginx \
        openssl \
        procps \
        net-tools \
    && rm -rf /var/lib/apt/lists/*

    #remove debian default config
RUN rm -f /etc/nginx/sites-enabled/default

    # we use a template for a dynamic config to keep variables flexible
COPY conf/nginx.conf.template /etc/nginx/nginx.conf.template
COPY tools/init.sh /usr/local/bin/init.sh

RUN chmod +x /usr/local/bin/init.sh

ENTRYPOINT ["/usr/local/bin/init.sh"]

CMD ["nginx", "-g", "daemon off;"]