# 23_NICK_overlong_line_disconnect.spec
# Malicious actor sends an overlength line exceeding 512 bytes on NICK.
# Expected: Server forcibly terminates the malformed client connection per 512-byte limit.
CLIENTS C1, C2

# C2 is a regular client
C2 SEND PASS 1234
C2 SEND NICK Bob205
C2 SEND USER u205 0 * :Bob205 23
C2 EXPECT 001 Bob205 :*

# C1 sends > 512 bytes without \r\n
C1 SEND PASS 1234
C1 SEND_RAW NICK AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
C1 EXPECT_DISCONNECT

# C2 remains healthy and fully responsive
C2 SEND PING localhost
C2 EXPECT :localhost PONG localhost :localhost
C2 EXPECT_CONNECTED
